server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: orderSnack
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**
        - id: orderManagement
          uri: http://localhost:8082
          predicates:
            - Path=/cookings/**/cancellations/**
        - id: notification
          uri: http://localhost:8083
          predicates:
            - Path=
        - id: orderView
          uri: http://localhost:8084
          predicates:
            - Path= /orderLists/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: orderSnack
          uri: http://orderSnack:8080
          predicates:
            - Path=/orders/**
        - id: orderManagement
          uri: http://orderManagement:8080
          predicates:
            - Path=/cookings/**/cancellations/**
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=
        - id: orderView
          uri: http://orderView:8080
          predicates:
            - Path= /orderLists/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
