apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderSnack
  labels:
    app: orderSnack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderSnack
  template:
    metadata:
      labels:
        app: orderSnack
    spec:
      containers:
        - name: orderSnack
          image: username/orderSnack:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5